
server:
  port: 8086
  context-path: /sb
  jsp-servlet:
    init-parameters:
      development: true





spring:
  profiles:
    active: dev
  mvc:
    view:
      suffix: .jsp
      prefix: /
  datasource:        #数据源的配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm
    password: 123456
    username: root
  http:
    multipart:
      max-file-size: 10000kb   #配置上传文件大小限制
      max-request-size: 20000kb







name: nameLILI
age:  44
qqs: 2229877,729912287,3348768
strs:  lili222,xixi222,wawa3333
map:  "{driver:'com.mysql.jdbc.Driver',url:'jdbc:mysql://localhost:3306/ssm'}"


user:
  id: 123
  namea: nameLIlI
  age: 22
  bir: 2020/12/12


user03:
  id: 333
  namea: nameLIlI
  age: 22
  bir: 2020/12/12
  maps:
    aa: aa001
    bb: bb002


mybatis:    #mybatis 配置数据映射文件的配置
  mapper-locations: classpath:com/tz/leo/springboot/mapper/*.xml
  type-aliases-package: com.tz.leo.springboot.entity



